create table if not exists public.stabilization_records (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  project_id uuid not null references public.projects(id) on delete restrict,
  project_service_id uuid not null references public.project_services(id) on delete restrict,
  observation_record_id uuid not null references public.observation_records(id) on delete restrict,
  deployment_record_id uuid not null references public.deployment_records(id) on delete restrict,
  implementation_record_id uuid not null references public.implementation_records(id) on delete restrict,
  delivery_activation_id uuid not null references public.delivery_activations(id) on delete restrict,
  entitlement_id uuid not null references public.entitlements(id) on delete restrict,
  stabilization_reference text not null check (length(btrim(stabilization_reference)) between 8 and 256),
  idempotency_key text not null check (length(btrim(idempotency_key)) between 8 and 128),
  stabilization_snapshot jsonb not null check (jsonb_typeof(stabilization_snapshot) = 'object'),
  status text not null default 'ACTIVE' check (status in ('ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED')),
  started_at timestamptz not null default timezone('utc', now()),
  paused_at timestamptz,
  completed_at timestamptz,
  status_reason text,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (observation_record_id),
  unique (organization_id, idempotency_key),
  check (completed_at is null or completed_at >= started_at)
);

create index if not exists stabilization_records_organization_created_at_idx on public.stabilization_records (organization_id, created_at desc);
create index if not exists stabilization_records_project_status_idx on public.stabilization_records (project_id, status, created_at desc);
create index if not exists stabilization_records_observation_idx on public.stabilization_records (observation_record_id, created_at desc);
create index if not exists stabilization_records_deployment_idx on public.stabilization_records (deployment_record_id, created_at desc);

alter table public.audit_events add column if not exists stabilization_record_id uuid references public.stabilization_records(id) on delete set null;
alter table public.audit_events drop constraint if exists audit_events_event_type_valid;
alter table public.audit_events add constraint audit_events_event_type_valid check (event_type in (
  'membership_created', 'membership_activated', 'membership_role_changed', 'membership_suspended', 'membership_removed', 'invitation_created', 'invitation_accepted', 'invitation_revoked', 'invitation_expired',
  'project_created', 'project_updated', 'project_archived', 'project_membership_created', 'project_membership_activated', 'project_membership_role_changed', 'project_membership_suspended', 'project_membership_removed', 'project_service_requested', 'project_service_updated',
  'proposal_created', 'proposal_version_created', 'proposal_issued', 'proposal_accepted', 'proposal_rejected', 'proposal_cancelled', 'agreement_created', 'agreement_version_created', 'agreement_accepted', 'agreement_activated', 'agreement_terminated',
  'payment_obligation_created', 'payment_obligation_cancelled', 'payment_obligation_expired', 'payment_attempt_created', 'payment_attempt_transitioned', 'entitlement_activated', 'entitlement_paused', 'entitlement_resumed', 'entitlement_expired', 'entitlement_cancelled',
  'delivery_activation_activated', 'delivery_activation_paused', 'delivery_activation_resumed', 'delivery_activation_completed', 'delivery_activation_cancelled', 'implementation_initialized', 'implementation_paused', 'implementation_resumed', 'implementation_completed', 'implementation_cancelled',
  'deployment_initialized', 'deployment_paused', 'deployment_resumed', 'deployment_completed', 'deployment_cancelled', 'observation_initialized', 'observation_paused', 'observation_resumed', 'observation_completed', 'observation_cancelled',
  'stabilization_initialized', 'stabilization_paused', 'stabilization_resumed', 'stabilization_completed', 'stabilization_cancelled'
));
create index if not exists audit_events_stabilization_record_created_at_idx on public.audit_events (stabilization_record_id, created_at);

create or replace function public.set_stabilization_record_updated_at() returns trigger language plpgsql set search_path = public, pg_temp as $$ begin new.updated_at = timezone('utc', now()); return new; end; $$;
drop trigger if exists set_stabilization_records_updated_at on public.stabilization_records;
create trigger set_stabilization_records_updated_at before update on public.stabilization_records for each row execute procedure public.set_stabilization_record_updated_at();

create or replace function private.record_stabilization_audit(p_event_type text, p_organization_id uuid, p_project_id uuid, p_project_service_id uuid, p_delivery_activation_id uuid, p_entitlement_id uuid, p_stabilization_record_id uuid, p_metadata jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path = public, pg_temp as $$ begin insert into public.audit_events (event_type, actor_user_id, organization_id, project_id, project_service_id, delivery_activation_id, entitlement_id, stabilization_record_id, metadata) values (p_event_type, (select auth.uid()), p_organization_id, p_project_id, p_project_service_id, p_delivery_activation_id, p_entitlement_id, p_stabilization_record_id, coalesce(p_metadata, '{}'::jsonb)); end; $$;
revoke all on function private.record_stabilization_audit(text, uuid, uuid, uuid, uuid, uuid, uuid, jsonb) from public;
revoke execute on function private.record_stabilization_audit(text, uuid, uuid, uuid, uuid, uuid, uuid, jsonb) from anon;

create or replace function public.initialize_stabilization(p_observation_record_id uuid, p_stabilization_reference text, p_idempotency_key text, p_stabilization_snapshot jsonb default '{}'::jsonb, p_actor_user_id uuid default null)
returns public.stabilization_records language plpgsql security definer set search_path = public, private, pg_temp as $$
declare actor_id uuid; observation public.observation_records; deployment public.deployment_records; implementation public.implementation_records; activation public.delivery_activations; entitlement public.entitlements; existing public.stabilization_records; created public.stabilization_records; ref text; idem text;
begin
  actor_id := coalesce((select auth.uid()), p_actor_user_id); if actor_id is null or not exists (select 1 from auth.users where id = actor_id) then raise exception using errcode = '42501', message = 'A valid trusted stabilization actor is required.'; end if;
  ref := btrim(coalesce(p_stabilization_reference, '')); idem := btrim(coalesce(p_idempotency_key, ''));
  if length(ref) < 8 or length(ref) > 256 or length(idem) < 8 or length(idem) > 128 then raise exception using errcode = '22023', message = 'Stabilization identity is invalid.'; end if;
  if jsonb_typeof(coalesce(p_stabilization_snapshot, '{}'::jsonb)) <> 'object' then raise exception using errcode = '22023', message = 'Stabilization snapshot must be a JSON object.'; end if;
  select * into observation from public.observation_records where id = p_observation_record_id for share; if not found or observation.status <> 'ACTIVE' then raise exception using errcode = '22023', message = 'Stabilization requires an active observation record.'; end if;
  select * into deployment from public.deployment_records where id = observation.deployment_record_id for share; if not found or deployment.status <> 'ACTIVE' then raise exception using errcode = '22023', message = 'Stabilization requires an active deployment record.'; end if;
  select * into implementation from public.implementation_records where id = observation.implementation_record_id for share; if not found or implementation.status <> 'ACTIVE' then raise exception using errcode = '22023', message = 'Stabilization requires an active implementation record.'; end if;
  select * into activation from public.delivery_activations where id = observation.delivery_activation_id for share; if not found or activation.status <> 'ACTIVE' then raise exception using errcode = '22023', message = 'Stabilization requires an active delivery activation.'; end if;
  select * into entitlement from public.entitlements where id = observation.entitlement_id for share; if not found or entitlement.status <> 'ACTIVE' then raise exception using errcode = '22023', message = 'Stabilization requires an active entitlement.'; end if;
  if observation.organization_id is distinct from deployment.organization_id or observation.project_id is distinct from deployment.project_id or observation.project_service_id is distinct from deployment.project_service_id or observation.deployment_record_id is distinct from deployment.id or observation.implementation_record_id is distinct from implementation.id or observation.delivery_activation_id is distinct from activation.id or observation.entitlement_id is distinct from entitlement.id or activation.organization_id is distinct from entitlement.organization_id or activation.project_id is distinct from entitlement.project_id or activation.project_service_id is distinct from entitlement.project_service_id then raise exception using errcode = '42501', message = 'Stabilization upstream relationships do not match.'; end if;
  select * into existing from public.stabilization_records where organization_id = observation.organization_id and idempotency_key = idem for update;
  if found then if existing.observation_record_id is distinct from observation.id or existing.stabilization_reference is distinct from ref then raise exception using errcode = '23505', message = 'Stabilization idempotency key was already used for a different record.'; end if; return existing; end if;
  insert into public.stabilization_records (organization_id, project_id, project_service_id, observation_record_id, deployment_record_id, implementation_record_id, delivery_activation_id, entitlement_id, stabilization_reference, idempotency_key, stabilization_snapshot, created_by)
  values (observation.organization_id, observation.project_id, observation.project_service_id, observation.id, deployment.id, implementation.id, activation.id, entitlement.id, ref, idem, jsonb_build_object('observation_record_id', observation.id, 'deployment_record_id', deployment.id, 'implementation_record_id', implementation.id, 'delivery_activation_id', activation.id, 'entitlement_id', entitlement.id, 'stabilization_context', coalesce(p_stabilization_snapshot, '{}'::jsonb)), actor_id) returning * into created;
  perform private.record_stabilization_audit('stabilization_initialized', created.organization_id, created.project_id, created.project_service_id, created.delivery_activation_id, created.entitlement_id, created.id, jsonb_build_object('stabilization_reference', created.stabilization_reference)); return created;
end; $$;

create or replace function public.pause_stabilization_record(p_stabilization_record_id uuid, p_expected_status text default 'ACTIVE', p_status_reason text default null) returns public.stabilization_records language plpgsql security definer set search_path = public, private, pg_temp as $$ declare target public.stabilization_records; changed public.stabilization_records; begin select * into target from public.stabilization_records where id = p_stabilization_record_id for update; if not found then raise exception using errcode = 'P0002', message = 'Stabilization record was not found.'; end if; if not private.commercial_owner(target.organization_id) then raise exception using errcode = '42501', message = 'Only the organization owner can pause stabilization records.'; end if; if upper(btrim(coalesce(p_expected_status, ''))) <> target.status or target.status <> 'ACTIVE' then raise exception using errcode = '40001', message = 'Stabilization record is not active or has changed. Refresh and retry.'; end if; update public.stabilization_records set status = 'PAUSED', paused_at = timezone('utc', now()), status_reason = nullif(btrim(p_status_reason), '') where id = target.id returning * into changed; perform private.record_stabilization_audit('stabilization_paused', changed.organization_id, changed.project_id, changed.project_service_id, changed.delivery_activation_id, changed.entitlement_id, changed.id, jsonb_build_object('previous_status', target.status)); return changed; end; $$;
create or replace function public.resume_stabilization_record(p_stabilization_record_id uuid, p_expected_status text default 'PAUSED', p_status_reason text default null) returns public.stabilization_records language plpgsql security definer set search_path = public, private, pg_temp as $$ declare target public.stabilization_records; changed public.stabilization_records; begin select * into target from public.stabilization_records where id = p_stabilization_record_id for update; if not found then raise exception using errcode = 'P0002', message = 'Stabilization record was not found.'; end if; if not private.commercial_owner(target.organization_id) then raise exception using errcode = '42501', message = 'Only the organization owner can resume stabilization records.'; end if; if upper(btrim(coalesce(p_expected_status, ''))) <> target.status or target.status <> 'PAUSED' then raise exception using errcode = '40001', message = 'Stabilization record is not paused or has changed. Refresh and retry.'; end if; update public.stabilization_records set status = 'ACTIVE', paused_at = null, status_reason = nullif(btrim(p_status_reason), '') where id = target.id returning * into changed; perform private.record_stabilization_audit('stabilization_resumed', changed.organization_id, changed.project_id, changed.project_service_id, changed.delivery_activation_id, changed.entitlement_id, changed.id, jsonb_build_object('previous_status', target.status)); return changed; end; $$;
create or replace function public.complete_stabilization_record(p_stabilization_record_id uuid, p_expected_status text default 'ACTIVE', p_status_reason text default null) returns public.stabilization_records language plpgsql security definer set search_path = public, private, pg_temp as $$ declare target public.stabilization_records; changed public.stabilization_records; begin select * into target from public.stabilization_records where id = p_stabilization_record_id for update; if not found then raise exception using errcode = 'P0002', message = 'Stabilization record was not found.'; end if; if not private.commercial_owner(target.organization_id) then raise exception using errcode = '42501', message = 'Only the organization owner can complete stabilization records.'; end if; if upper(btrim(coalesce(p_expected_status, ''))) <> target.status or target.status not in ('ACTIVE', 'PAUSED') then raise exception using errcode = '40001', message = 'Stabilization record is not active/paused or has changed. Refresh and retry.'; end if; update public.stabilization_records set status = 'COMPLETED', completed_at = timezone('utc', now()), status_reason = nullif(btrim(p_status_reason), '') where id = target.id returning * into changed; perform private.record_stabilization_audit('stabilization_completed', changed.organization_id, changed.project_id, changed.project_service_id, changed.delivery_activation_id, changed.entitlement_id, changed.id, jsonb_build_object('previous_status', target.status)); return changed; end; $$;
create or replace function public.cancel_stabilization_record(p_stabilization_record_id uuid, p_expected_status text default 'ACTIVE', p_status_reason text default null) returns public.stabilization_records language plpgsql security definer set search_path = public, private, pg_temp as $$ declare target public.stabilization_records; changed public.stabilization_records; begin select * into target from public.stabilization_records where id = p_stabilization_record_id for update; if not found then raise exception using errcode = 'P0002', message = 'Stabilization record was not found.'; end if; if not private.commercial_owner(target.organization_id) then raise exception using errcode = '42501', message = 'Only the organization owner can cancel stabilization records.'; end if; if upper(btrim(coalesce(p_expected_status, ''))) <> target.status or target.status not in ('ACTIVE', 'PAUSED') then raise exception using errcode = '40001', message = 'Stabilization record is not active/paused or has changed. Refresh and retry.'; end if; update public.stabilization_records set status = 'CANCELLED', status_reason = nullif(btrim(p_status_reason), '') where id = target.id returning * into changed; perform private.record_stabilization_audit('stabilization_cancelled', changed.organization_id, changed.project_id, changed.project_service_id, changed.delivery_activation_id, changed.entitlement_id, changed.id, jsonb_build_object('previous_status', target.status)); return changed; end; $$;

create or replace function private.prevent_stabilization_record_mutation() returns trigger language plpgsql security definer set search_path = public, pg_temp as $$ begin if tg_op = 'DELETE' then raise exception using errcode = '42501', message = 'Stabilization history cannot be deleted.'; end if; if old.id is distinct from new.id or old.organization_id is distinct from new.organization_id or old.project_id is distinct from new.project_id or old.project_service_id is distinct from new.project_service_id or old.observation_record_id is distinct from new.observation_record_id or old.deployment_record_id is distinct from new.deployment_record_id or old.implementation_record_id is distinct from new.implementation_record_id or old.delivery_activation_id is distinct from new.delivery_activation_id or old.entitlement_id is distinct from new.entitlement_id or old.stabilization_reference is distinct from new.stabilization_reference or old.idempotency_key is distinct from new.idempotency_key or old.stabilization_snapshot is distinct from new.stabilization_snapshot or old.started_at is distinct from new.started_at or old.created_by is distinct from new.created_by or old.created_at is distinct from new.created_at then raise exception using errcode = '42501', message = 'Stabilization source and configuration fields are immutable.'; end if; if new.status is distinct from old.status and not ((old.status = 'ACTIVE' and new.status in ('PAUSED', 'COMPLETED', 'CANCELLED')) or (old.status = 'PAUSED' and new.status in ('ACTIVE', 'COMPLETED', 'CANCELLED'))) then raise exception using errcode = '22023', message = 'Stabilization lifecycle transition is not allowed.'; end if; return new; end; $$;
revoke all on function private.prevent_stabilization_record_mutation() from public;
revoke execute on function private.prevent_stabilization_record_mutation() from anon;
drop trigger if exists prevent_stabilization_record_mutation on public.stabilization_records;
create trigger prevent_stabilization_record_mutation before update or delete on public.stabilization_records for each row execute procedure private.prevent_stabilization_record_mutation();

revoke all on function public.initialize_stabilization(uuid, text, text, jsonb, uuid) from public;
revoke execute on function public.initialize_stabilization(uuid, text, text, jsonb, uuid) from anon, authenticated;
grant execute on function public.initialize_stabilization(uuid, text, text, jsonb, uuid) to service_role;
revoke all on function public.pause_stabilization_record(uuid, text, text) from public;
revoke all on function public.resume_stabilization_record(uuid, text, text) from public;
revoke all on function public.complete_stabilization_record(uuid, text, text) from public;
revoke all on function public.cancel_stabilization_record(uuid, text, text) from public;
revoke execute on function public.pause_stabilization_record(uuid, text, text) from anon;
revoke execute on function public.resume_stabilization_record(uuid, text, text) from anon;
revoke execute on function public.complete_stabilization_record(uuid, text, text) from anon;
revoke execute on function public.cancel_stabilization_record(uuid, text, text) from anon;
grant execute on function public.pause_stabilization_record(uuid, text, text) to authenticated;
grant execute on function public.resume_stabilization_record(uuid, text, text) to authenticated;
grant execute on function public.complete_stabilization_record(uuid, text, text) to authenticated;
grant execute on function public.cancel_stabilization_record(uuid, text, text) to authenticated;

alter table public.stabilization_records enable row level security;
create policy "Accessible members can view stabilization records" on public.stabilization_records for select to authenticated using (private.has_organization_role(organization_id, 'MEMBER') and private.has_project_access(project_id));
create policy "Stabilization record inserts require trusted functions" on public.stabilization_records for insert to authenticated with check (false);
create policy "Stabilization record updates require trusted functions" on public.stabilization_records for update to authenticated using (false) with check (false);
create policy "Stabilization record deletes are disabled" on public.stabilization_records for delete to authenticated using (false);

comment on table public.stabilization_records is 'Provider-neutral paid implementation stabilization record initialized only from a valid active observation and complete upstream lifecycle chain. It does not automate monitoring or remediation.';
comment on function public.initialize_stabilization(uuid, text, text, jsonb, uuid) is 'Service-role-only stabilization initialization boundary requiring active entitlement, delivery activation, implementation, deployment, and observation records.';