create table if not exists public.documentation_records (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete restrict, project_id uuid not null references public.projects(id) on delete restrict, project_service_id uuid not null references public.project_services(id) on delete restrict, stabilization_record_id uuid not null references public.stabilization_records(id) on delete restrict, observation_record_id uuid not null references public.observation_records(id) on delete restrict, deployment_record_id uuid not null references public.deployment_records(id) on delete restrict, implementation_record_id uuid not null references public.implementation_records(id) on delete restrict, delivery_activation_id uuid not null references public.delivery_activations(id) on delete restrict, entitlement_id uuid not null references public.entitlements(id) on delete restrict, documentation_reference text not null check (length(btrim(documentation_reference)) between 8 and 256), idempotency_key text not null check (length(btrim(idempotency_key)) between 8 and 128), documentation_snapshot jsonb not null check (jsonb_typeof(documentation_snapshot) = 'object'), status text not null default 'ACTIVE' check (status in ('ACTIVE','PAUSED','COMPLETED','CANCELLED')), started_at timestamptz not null default timezone('utc',now()), paused_at timestamptz, completed_at timestamptz, status_reason text, created_by uuid not null references auth.users(id) on delete restrict, created_at timestamptz not null default timezone('utc',now()), updated_at timestamptz not null default timezone('utc',now()), unique(stabilization_record_id), unique(organization_id,idempotency_key), check(completed_at is null or completed_at >= started_at)
);
create index if not exists documentation_records_project_status_idx on public.documentation_records(project_id,status,created_at desc);
alter table public.audit_events add column if not exists documentation_record_id uuid references public.documentation_records(id) on delete set null;
alter table public.audit_events drop constraint if exists audit_events_event_type_valid;
alter table public.audit_events add constraint audit_events_event_type_valid check (event_type in ('membership_created','membership_activated','membership_role_changed','membership_suspended','membership_removed','invitation_created','invitation_accepted','invitation_revoked','invitation_expired','project_created','project_updated','project_archived','project_membership_created','project_membership_activated','project_membership_role_changed','project_membership_suspended','project_membership_removed','project_service_requested','project_service_updated','proposal_created','proposal_version_created','proposal_issued','proposal_accepted','proposal_rejected','proposal_cancelled','agreement_created','agreement_version_created','agreement_accepted','agreement_activated','agreement_terminated','payment_obligation_created','payment_obligation_cancelled','payment_obligation_expired','payment_attempt_created','payment_attempt_transitioned','entitlement_activated','entitlement_paused','entitlement_resumed','entitlement_expired','entitlement_cancelled','delivery_activation_activated','delivery_activation_paused','delivery_activation_resumed','delivery_activation_completed','delivery_activation_cancelled','implementation_initialized','implementation_paused','implementation_resumed','implementation_completed','implementation_cancelled','deployment_initialized','deployment_paused','deployment_resumed','deployment_completed','deployment_cancelled','observation_initialized','observation_paused','observation_resumed','observation_completed','observation_cancelled','stabilization_initialized','stabilization_paused','stabilization_resumed','stabilization_completed','stabilization_cancelled','documentation_initialized','documentation_paused','documentation_resumed','documentation_completed','documentation_cancelled'));
create index if not exists audit_events_documentation_record_idx on public.audit_events(documentation_record_id,created_at);
alter table public.documentation_records enable row level security;
create policy "Accessible members can view documentation records" on public.documentation_records for select to authenticated using(private.has_organization_role(organization_id,'MEMBER') and private.has_project_access(project_id));
create policy "Documentation inserts require trusted functions" on public.documentation_records for insert to authenticated with check(false);
create policy "Documentation updates require trusted functions" on public.documentation_records for update to authenticated using(false) with check(false);
create policy "Documentation deletes are disabled" on public.documentation_records for delete to authenticated using(false);
comment on table public.documentation_records is 'Documentation lifecycle foundation within paid implementation; no document generation or storage.';
